apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: Cloud
  type: core.Directory
  children:
  - name: Terraform
    type: core.Directory
    children:
    - name: tf_azure.conf
      type: udm.Dictionary
      entries:        
        servers: 1      
      encryptedEntries:        
        subscription_id: !value azure_subscription_id
        tenant_id: !value azure_tenant_id