apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: Cloud
  type: core.Directory
  children:
  - name: Terraform
    type: core.Directory
    children: 
    - name: Terraform AWS
      type: udm.Environment
      members:
      - ~Infrastructure/Cloud/Terraform/terraform-host/terraform-aws-client
      dictionaries:
      - ~Environments/Cloud/Terraform/tf_aws.conf