apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: Cloud
  type: core.Directory
  children:
  - name: Terraform
    type: core.Directory
    children:
    - name: terraform-host
      type: overthere.LocalHost
      os: UNIX
      children:
      - name: terraform-aws-client
        type: terraform.TerraformClient
        workingDirectory: /tmp/terraform_by_xldeploy_for_aws
    

